In [1]:
#1
import numpy as np

myArray = np.array([[1, 2, 3], [4, 5, 6]])
myList = myArray.tolist()
print(myArray)
print(myList)

[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]


In [2]:
#2
a=np.array([[1,4,9],[1,8,3],[1,4,6]])
a.diagonal().sum()

15

In [3]:
#2
import numpy as np

myArray = np.eye(11)
sum = np.trace(myArray)
print(sum)

11.0


In [6]:
import numpy as np

a = 0
x = 3

myArray = np.array([[1, 2, 3], [4, 5, 6]])
emptyList = []
length = myArray.shape[1]
print(length)
print(myArray)



3
[[1 2 3]
 [4 5 6]]


In [13]:
for i in range(myArray.shape[0]):
    for j in range(myArray.shape[1]):
         if i[j] > x:
            emptyList.append(i[a])
            
        if a == length:
             = 0

resultArray = np.array(emptyList)
  


#print(resultArray)


1
2
3
4
5
6


In [14]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([3, 2, 1])
C = np.add(A, B)

print(C)

[4 4 4]


In [15]:
import numpy as np

x = np.random.random((1, 3))
y = x.mean()
z = x - y
print(z)

[[ 0.40493147 -0.12345539 -0.28147608]]
